import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const KCODER_EXPERIMENTAL = truthy("KCODER_EXPERIMENTAL")
const KCODER_DISABLE_CLAUDE_CODE = truthy("KCODER_DISABLE_CLAUDE_CODE")
const KCODER_DISABLE_CLAUDE_CODE_SKILLS =
  KCODER_DISABLE_CLAUDE_CODE || truthy("KCODER_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["KCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  KCODER_AUTO_SHARE: truthy("KCODER_AUTO_SHARE"),
  KCODER_AUTO_HEAP_SNAPSHOT: truthy("KCODER_AUTO_HEAP_SNAPSHOT"),
  KCODER_GIT_BASH_PATH: process.env["KCODER_GIT_BASH_PATH"],
  KCODER_CONFIG: process.env["KCODER_CONFIG"],
  KCODER_CONFIG_CONTENT: process.env["KCODER_CONFIG_CONTENT"],
  KCODER_DISABLE_AUTOUPDATE: truthy("KCODER_DISABLE_AUTOUPDATE"),
  KCODER_ALWAYS_NOTIFY_UPDATE: truthy("KCODER_ALWAYS_NOTIFY_UPDATE"),
  KCODER_DISABLE_PRUNE: truthy("KCODER_DISABLE_PRUNE"),
  KCODER_DISABLE_TERMINAL_TITLE: truthy("KCODER_DISABLE_TERMINAL_TITLE"),
  KCODER_SHOW_TTFD: truthy("KCODER_SHOW_TTFD"),
  KCODER_PERMISSION: process.env["KCODER_PERMISSION"],
  KCODER_DISABLE_DEFAULT_PLUGINS: truthy("KCODER_DISABLE_DEFAULT_PLUGINS"),
  KCODER_DISABLE_LSP_DOWNLOAD: truthy("KCODER_DISABLE_LSP_DOWNLOAD"),
  KCODER_ENABLE_EXPERIMENTAL_MODELS: truthy("KCODER_ENABLE_EXPERIMENTAL_MODELS"),
  KCODER_DISABLE_AUTOCOMPACT: truthy("KCODER_DISABLE_AUTOCOMPACT"),
  KCODER_DISABLE_MODELS_FETCH: truthy("KCODER_DISABLE_MODELS_FETCH"),
  KCODER_DISABLE_MOUSE: truthy("KCODER_DISABLE_MOUSE"),
  KCODER_DISABLE_CLAUDE_CODE,
  KCODER_DISABLE_CLAUDE_CODE_PROMPT: KCODER_DISABLE_CLAUDE_CODE || truthy("KCODER_DISABLE_CLAUDE_CODE_PROMPT"),
  KCODER_DISABLE_CLAUDE_CODE_SKILLS,
  KCODER_DISABLE_EXTERNAL_SKILLS: KCODER_DISABLE_CLAUDE_CODE_SKILLS || truthy("KCODER_DISABLE_EXTERNAL_SKILLS"),
  KCODER_FAKE_VCS: process.env["KCODER_FAKE_VCS"],
  KCODER_SERVER_PASSWORD: process.env["KCODER_SERVER_PASSWORD"],
  KCODER_SERVER_USERNAME: process.env["KCODER_SERVER_USERNAME"],
  KCODER_ENABLE_QUESTION_TOOL: truthy("KCODER_ENABLE_QUESTION_TOOL"),

  // Experimental
  KCODER_EXPERIMENTAL,
  KCODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("KCODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  KCODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("KCODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  KCODER_EXPERIMENTAL_ICON_DISCOVERY: KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_ICON_DISCOVERY"),
  KCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("KCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  KCODER_ENABLE_EXA: truthy("KCODER_ENABLE_EXA") || KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_EXA"),
  KCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("KCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  KCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("KCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  KCODER_EXPERIMENTAL_OXFMT: KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_OXFMT"),
  KCODER_EXPERIMENTAL_LSP_TY: truthy("KCODER_EXPERIMENTAL_LSP_TY"),
  KCODER_EXPERIMENTAL_LSP_TOOL: KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_LSP_TOOL"),
  KCODER_EXPERIMENTAL_PLAN_MODE: KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_PLAN_MODE"),
  KCODER_EXPERIMENTAL_MARKDOWN: !falsy("KCODER_EXPERIMENTAL_MARKDOWN"),
  KCODER_MODELS_URL: process.env["KCODER_MODELS_URL"],
  KCODER_MODELS_PATH: process.env["KCODER_MODELS_PATH"],
  KCODER_DISABLE_EMBEDDED_WEB_UI: truthy("KCODER_DISABLE_EMBEDDED_WEB_UI"),
  KCODER_DB: process.env["KCODER_DB"],
  KCODER_DISABLE_CHANNEL_DB: truthy("KCODER_DISABLE_CHANNEL_DB"),
  KCODER_SKIP_MIGRATIONS: truthy("KCODER_SKIP_MIGRATIONS"),
  KCODER_STRICT_CONFIG_DEPS: truthy("KCODER_STRICT_CONFIG_DEPS"),

  KCODER_WORKSPACE_ID: process.env["KCODER_WORKSPACE_ID"],
  KCODER_EXPERIMENTAL_HTTPAPI: truthy("KCODER_EXPERIMENTAL_HTTPAPI"),
  KCODER_EXPERIMENTAL_WORKSPACES: KCODER_EXPERIMENTAL || truthy("KCODER_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get KCODER_DISABLE_PROJECT_CONFIG() {
    return truthy("KCODER_DISABLE_PROJECT_CONFIG")
  },
  get KCODER_TUI_CONFIG() {
    return process.env["KCODER_TUI_CONFIG"]
  },
  get KCODER_CONFIG_DIR() {
    return process.env["KCODER_CONFIG_DIR"]
  },
  get KCODER_PURE() {
    return truthy("KCODER_PURE")
  },
  get KCODER_PLUGIN_META_FILE() {
    return process.env["KCODER_PLUGIN_META_FILE"]
  },
  get KCODER_CLIENT() {
    return process.env["KCODER_CLIENT"] ?? "cli"
  },
}
